# Generated by Django 6.0.7 on 2026-07-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline for the hero banner ad', max_length=255)),
                ('subtitle', models.TextField(blank=True, help_text='Supporting description or promo offer text')),
                ('badge_text', models.CharField(blank=True, help_text='Small pill badge text e.g., LIMITED TIME ONLY', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='High-resolution banner background image file', null=True, upload_to='hero_banners/')),
                ('image_url', models.URLField(blank=True, help_text='Optional external image URL if no file is uploaded', max_length=500, null=True)),
                ('button_text', models.CharField(default='Shop Collection', max_length=50)),
                ('button_link', models.CharField(default='/product/', max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, default='Explore Deals', max_length=50)),
                ('secondary_button_link', models.CharField(blank=True, default='/product/', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this ad from the hero carousel')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in carousel (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner Ad',
                'verbose_name_plural': 'Hero Banner Ads',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
