# Generated by Django 6.0.7 on 2026-07-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='discount_tag',
            field=models.CharField(blank=True, default='UP TO 50% OFF', help_text='Promo tag e.g. UP TO 60% OFF or EXTRA 20% DISCOUNT', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='rating_text',
            field=models.CharField(blank=True, default='4.9 ★ (15k+ Reviews)', help_text='Floating trust rating label', max_length=100),
        ),
    ]
