# Generated by Django 6.0.7 on 2026-07-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herobanner_discount_tag_herobanner_rating_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='discount_tag',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='rating_text',
        ),
    ]
