# Generated by Django 6.0.7 on 2026-07-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_herobanner_discount_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name (e.g. DAALI, Libas, Nike, Zara)', max_length=150)),
                ('logo_text', models.CharField(blank=True, help_text='Custom logo text or markup to display on card', max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Brand card background image file', null=True, upload_to='brand_spotlights/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True)),
                ('discount_tag', models.CharField(help_text='Promotional caption (e.g. MIN. 40% OFF, UNDER ₹999)', max_length=100)),
                ('link', models.CharField(default='/product/', help_text='Destination link for card click', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this spotlight card')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers display first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand Spotlight',
                'verbose_name_plural': 'Brand Spotlights',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
