# Generated by Django 6.0.7 on 2026-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brandspotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandspotlight',
            name='category',
            field=models.CharField(choices=[('women', "Women's Spotlight"), ('men', "Men's Spotlight")], default='women', help_text="Target category section (Women's or Men's)", max_length=20),
        ),
    ]
