# Generated by Django 6.0.7 on 2026-07-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brandspotlight_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category or Brand name (e.g. Nike, Zara, Electronics)', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug (auto-generated from name)', max_length=160, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional category description')),
                ('image', models.ImageField(blank=True, help_text='Category thumbnail image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this category from marketplace listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='brandspotlight',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Associated product category/brand model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_spotlights', to='core.category'),
        ),
    ]
