# Generated by Django 6.0.7 on 2026-07-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_brandspotlight_category_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Category title (e.g. KURTAS & SUIT SETS, DRESSES, FORMAL MENSWEAR)', max_length=150)),
                ('brand_sub_title', models.CharField(blank=True, help_text='Sub title/brand for promo card (e.g. WESTSIDE / MARKETPLACE)', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Category image file', null=True, upload_to='featured_categories/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True)),
                ('is_promo_card', models.BooleanField(default=False, help_text='Check if this card is a solid promo banner (like Pink Sale card)')),
                ('promo_bg_color', models.CharField(default='#d81b60', help_text='Background color hex for promo card (e.g. #d81b60)', max_length=30)),
                ('link', models.CharField(default='/product/', help_text='Destination link for card click', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide card')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers display first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_ref', models.ForeignKey(blank=True, help_text='Linked Category model for product filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_cards', to='core.category')),
            ],
            options={
                'verbose_name': 'Featured Category Card',
                'verbose_name_plural': 'Featured Category Cards',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
