# Generated by Django 6.0.7 on 2026-07-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_featuredcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandspotlight',
            name='parent_categories',
            field=models.ManyToManyField(blank=True, help_text='Parent categories featuring this brand (e.g. Formal Menswear -> Calvin Klein, Polo)', related_name='featured_brands', to='core.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (e.g. Formal Menswear -> Polo, Calvin Klein, Hugo Boss)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category'),
        ),
        migrations.AlterField(
            model_name='brandspotlight',
            name='category_ref',
            field=models.ForeignKey(blank=True, help_text='Linked Category model for product filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_spotlights', to='core.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category or Brand name (e.g. Formal Menswear, Nike, Zara)', max_length=150, unique=True),
        ),
    ]
