# Generated by Django 6.0.7 on 2026-07-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_brandspotlight_parent_categories_category_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title (e.g. WOMENSWEAR, HIS FOOTWEAR)', max_length=150)),
                ('offer_tag', models.CharField(blank=True, help_text='Offer text (e.g. UP TO 70% OFF, MIN. 40% OFF)', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Category image file', null=True, upload_to='shop_drop/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True)),
                ('is_promo_card', models.BooleanField(default=False, help_text='Check if this card is a solid promo box (Pink SALE card)')),
                ('promo_bg_color', models.CharField(default='#d81b60', help_text='Background color hex for promo card', max_length=30)),
                ('promo_brand_text', models.CharField(default='MARKETPLACE', help_text='Sub title text for promo card (e.g. WESTSIDE / MARKETPLACE)', max_length=100)),
                ('promo_caption', models.CharField(default='EXPRESS SHIPPING', help_text='Bottom caption for promo card', max_length=100)),
                ('link', models.CharField(default='/product/', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_ref', models.ForeignKey(blank=True, help_text='Linked Category model for product filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_drop_items', to='core.category')),
            ],
            options={
                'verbose_name': 'Shop Drop Card',
                'verbose_name_plural': 'Shop Drop Cards',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
