# Generated by Django 6.0.7 on 2026-07-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_shopdrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Brand name e.g., Jockey, Nike, Calvin Klein', max_length=150)),
                ('title', models.CharField(help_text='Full product title', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Original MRP price', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Discounted selling price', max_digits=10)),
                ('rating', models.FloatField(default=4.5, help_text='Star rating out of 5.0')),
                ('ratings_count', models.PositiveIntegerField(default=12, help_text='Total ratings count')),
                ('reviews_count', models.PositiveIntegerField(default=3, help_text='Total reviews count')),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('size_guidelines', models.TextField(blank=True, default='Please check size chart table to know the exact size to be ordered.')),
                ('offers_text', models.CharField(blank=True, default='Hurry! Get 5% Cashback. Offer ends tonight.', max_length=255)),
                ('seller_name', models.CharField(default='1 PAGE INDUSTRIES LIMITED', max_length=200)),
                ('delivery_info', models.CharField(default='Delivery by 3rd Aug', max_length=200)),
                ('return_policy', models.CharField(default='7 Days Return and Replacement available', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='Color name e.g. Orchid Smoke, Midnight Navy', max_length=100)),
                ('color_code', models.CharField(default='#000000', help_text='Hex code e.g. #D4829C', max_length=30)),
                ('swatch_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('angle_label', models.CharField(default='Front View', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productcolor')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(help_text='Size e.g. 32B, 34C, S, M, L, 42', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='product.product')),
            ],
        ),
    ]
