# Generated by Django 6.0.7 on 2026-08-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_rating_alter_product_ratings_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, help_text='Available stock quantity'),
        ),
    ]
