# Generated by Django 6.0.6 on 2026-08-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_products/'),
        ),
    ]
