# Generated by Django 6.0.6 on 2026-08-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_productrequest_image_url_productrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='color_code',
            field=models.CharField(blank=True, default='#000000', max_length=30),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='color_name',
            field=models.CharField(blank=True, default='Default', max_length=100),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='delivery_info',
            field=models.CharField(blank=True, default='Delivery by 3rd Aug', max_length=200),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='seller_products/'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='seller_products/'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='offers_text',
            field=models.CharField(blank=True, default='Hurry! Get 5% Cashback. Offer ends tonight.', max_length=255),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='return_policy',
            field=models.CharField(blank=True, default='7 Days Return and Replacement available', max_length=200),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='size_guidelines',
            field=models.TextField(blank=True, default='Please check size chart table to know the exact size to be ordered.'),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='sizes',
            field=models.CharField(blank=True, default='', help_text='Comma-separated sizes, e.g. S,M,L,XL', max_length=255),
        ),
    ]
