# Generated by Django 6.0.6 on 2026-08-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_productrequest_color_code_productrequest_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='seller_products/'),
        ),
    ]
