# Generated by Django 6.0.7 on 2026-08-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_productrequest_image4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_index', models.PositiveIntegerField(default=0)),
                ('color_name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(upload_to='seller_products/')),
                ('angle_label', models.CharField(default='Front View', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seller.productrequest')),
            ],
            options={
                'ordering': ['color_index', 'order'],
            },
        ),
    ]
