# Generated by Django 6.0.7 on 2026-08-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_productrequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_vat_back',
            field=models.ImageField(blank=True, null=True, upload_to='seller_documents/', verbose_name='PAN / VAT Card Back Side'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_vat_front',
            field=models.ImageField(blank=True, null=True, upload_to='seller_documents/', verbose_name='PAN / VAT Card Front Side'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan_vat_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='PAN / VAT Number'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
