# Generated by Django 6.0.7 on 2026-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_sellerprofile_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Feedback or rejection reason from admin'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(choices=[('unapplied', 'Not Applied'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unapplied', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='pan_vat_back',
            field=models.ImageField(blank=True, null=True, upload_to='seller_documents/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='pan_vat_front',
            field=models.ImageField(blank=True, null=True, upload_to='seller_documents/'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='pan_vat_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
