# Generated by Django 6.0.7 on 2026-08-06 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_admin_note_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
